version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: whisper-server

    ports:
      - 7860:7860
      - 5678:5678
    volumes:
      - .:/workspace

    command: ./start.sh


